#
# 86Box-Next: the build number shown in the title bar.
#
# The last successful build's number is kept in FILE (.build-number in the
# repository root, not tracked by git).  Run with MODE=pre before a build: the
# generated header OUT gets that number plus one, rewritten only when it
# changes so nothing else rebuilds.  Run with MODE=post after the executable
# is linked: FILE takes the number the build used.  A build that fails never
# gets to post, so its number is used again by the next one.
#
#   cmake -DMODE=pre|post -DFILE=<counter> -DOUT=<header> -P NextBuildNumber.cmake
#

if(EXISTS "${FILE}")
    file(READ "${FILE}" last)
    string(STRIP "${last}" last)
endif()
if(NOT last MATCHES "^[0-9]+$")
    set(last 0)
endif()

if(MODE STREQUAL "pre")
    math(EXPR next "${last} + 1")
    set(content "/* Generated by cmake/NextBuildNumber.cmake -- do not edit. */\n#define NEXT_BUILD_NUMBER ${next}\n")
    if(EXISTS "${OUT}")
        file(READ "${OUT}" old)
    endif()
    if(NOT old STREQUAL content)
        file(WRITE "${OUT}" "${content}")
    endif()
elseif(MODE STREQUAL "post")
    file(READ "${OUT}" header)
    string(REGEX MATCH "NEXT_BUILD_NUMBER ([0-9]+)" _ "${header}")
    file(WRITE "${FILE}" "${CMAKE_MATCH_1}\n")
    message(STATUS "86Box-Next build ${CMAKE_MATCH_1}")
endif()
